common_cents/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("webapp.urls")),
    path("calculators/mortgage/", include("mortgage_calculator.urls")),
]

mortgage_calculator/urls.py
from django.urls import path
from . import views

app_name = "calculators"

urlpatterns = [
    path(
        "affordability",
        views.AffordabilityCalculatorView.as_view(),
        name="affordability_calculator",
    ),
    path(
        "overpayment",
        views.OverpaymentCalculatorView.as_view(),
        name="overpayment_calculator",
    ),
]

webapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

webapp/models.py
from django.db import models

# Create your models here.

mortgage_calculator/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .utils import calculate_overpayment_schedule


class AffordabilityCalculatorView(TemplateView):
    template_name = "mortgage_calculator/affordability.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["show_results"] = False
        return context

    def post(self, request, *args, **kwargs):
        income = float(request.POST.get("income"))
        expenses = float(request.POST.get("expenses"))
        deposit = float(request.POST.get("deposit"))
        interest_rate = (
            float(request.POST.get("interest_rate")) / 100 / 12
        )  # Monthly rate
        mortgage_term = int(request.POST.get("mortgage_term")) * 12

        # Example affordability calculation (customize as needed)
        # Assuming a certain percentage of income can be used for mortgage payments
        affordable_percentage = 0.4  # Example: 40%

        max_affordable_payment = (income * affordable_percentage) / 12 - expenses
        max_loan = (
            max_affordable_payment * ((1 + interest_rate) ** mortgage_term - 1)
        ) / (interest_rate * (1 + interest_rate) ** mortgage_term)
        monthly_payment = (
            max_loan * interest_rate * (1 + interest_rate) ** mortgage_term
        ) / ((1 + interest_rate) ** mortgage_term - 1)

        context = {
            "income": income,
            "expenses": expenses,
            "deposit": deposit,
            "interest_rate": interest_rate,
            "mortgage_term": mortgage_term / 12,
            "max_loan": round(max_loan, 2),
            "monthly_payment": round(monthly_payment, 2),
            "show_results": True,
        }
        return render(request, self.template_name, context)


class OverpaymentCalculatorView(TemplateView):
    template_name = "mortgage_calculator/overpayment.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["show_results"] = False
        return context

    def post(self, request, *args, **kwargs):
        cost_of_debt = float(request.POST.get("cost_of_debt"))
        mortgage_term = int(request.POST.get("mortgage_term"))
        interest_only = request.POST.get("mortgage_type") == "interest_only"
        interest_rate = float(request.POST.get("interest_rate")) / 100 / 12
        monthly_repayment = (
            float(request.POST.get("monthly_repayment"))
            if request.POST.get("monthly_repayment")
            else None
        )
        one_off_overpayment = (
            float(request.POST.get("one_off_overpayment"))
            if request.POST.get("one_off_overpayment")
            else 0
        )
        recurring_overpayment = (
            float(request.POST.get("recurring_overpayment"))
            if request.POST.get("recurring_overpayment")
            else 0
        )

        if interest_only:
            monthly_payment = cost_of_debt * interest_rate
            total_repayment = monthly_payment * mortgage_term
        else:
            if monthly_repayment:
                monthly_payment = monthly_repayment
                # TODO: investigate financial library
                total_repayment = monthly_payment * mortgage_term
            else:
                monthly_payment = (
                    cost_of_debt
                    * interest_rate
                    * (1 + interest_rate) ** (mortgage_term * 12)
                ) / ((1 + interest_rate) ** (mortgage_term * 12) - 1)
                total_repayment = monthly_payment * mortgage_term * 12

        # Overpayment calculations
        overpayment_schedule = calculate_overpayment_schedule(
            cost_of_debt,
            interest_rate,
            mortgage_term,
            monthly_payment,
            one_off_overpayment,
            recurring_overpayment,
        )

        context = {
            "cost_of_debt": cost_of_debt,
            "mortgage_term": mortgage_term,
            "interest_only": interest_only,
            "interest_rate": interest_rate,
            "monthly_payment": round(monthly_payment, 2),
            "total_repayment": round(total_repayment, 2),
            "one_off_overpayment": one_off_overpayment,
            "recurring_overpayment": recurring_overpayment,
            "overpayment_schedule": overpayment_schedule,
            "show_results": True,
        }
        return render(request, self.template_name, context)

webapp/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "webapp/index.html"

mortgage_calculator/templates/mortgage_calculator/affordability.html
{% extends "webapp/base.html" %}
{% load static %}

{% block title %}Affordability Calculator{% endblock %}
{% block heading %}Affordability Calculator{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'calculators:affordability_calculator' %}">Affordability Calculator</a></li>
{% endblock %}

{% block content %}
<div class="two-column-layout">
    <div class="form-column">
        <form method="post">
            {% csrf_token %}

            <label for="income">Annual Income (£):</label>
            <input type="number" name="income" required><br><br>

            <label for="expenses">Monthly Expenses (£):</label>
            <input type="number" name="expenses" required><br><br>

            <label for="deposit">Deposit Amount (£):</label>
            <input type="number" name="deposit" required><br><br>

            <label for="interest_rate">Interest Rate (%):</label>
            <input type="number" name="interest_rate" step="any" required><br><br>

            <label for="mortgage_term">Mortgage Term (Years):</label>
            <input type="number" name="mortgage_term" required><br><br>

            <button type="submit">Calculate</button>
        </form>
    </div>
    <div class="results-column">
        {% if show_results %}
        <h2>Results</h2>
        <p>Maximum Affordable Loan: £{{ max_loan }}</p>
        <p>Monthly Payment: £{{ monthly_payment }}</p>
        {% endif %}
    </div>
</div>
{% endblock %}

mortgage_calculator/templates/mortgage_calculator/overpayment.html
{% extends "webapp/base.html" %}
{% load static %}

{% block title %}Overpayment Calculator{% endblock %}
{% block heading %}Overpayment Calculator{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'calculators:overpayment_calculator' %}">Overpayment Calculator</a></li>
{% endblock %}

{% block content %}
<div class="two-column-layout">
    <div class="form-column">
        <form method="post">
            {% csrf_token %}
            <h2>Mortgage</h2>

            <label for="cost_of_debt">Cost of Mortgage Debt (£):</label>
            <input type="number" name="cost_of_debt" required><br><br>

            <label for="mortgage_term">Mortgage Term (Years):</label>
            <input type="number" name="mortgage_term" required><br><br>

            <label for="mortgage_type">Mortgage Type:</label>
            <select name="mortgage_type">
                <option value="repayment">Repayment</option>
                <option value="interest_only">Interest Only</option>
            </select><br><br>

            <label for="interest_rate">Interest Rate (%):</label>
            <input type="number" name="interest_rate" step="any" ><br><br>

            <label for="monthly_repayment">Monthly Repayment (£):</label>
            <input type="number" name="monthly_repayment" step="any" ><br><br>

            <h2>Overpayment</h2>
            <label for="one_off_overpayment">One-Off Overpayment (£):</label>
            <input type="number" name="one_off_overpayment" value="0"><br><br>

            <label for="recurring_overpayment">Recurring Monthly Overpayment (£):</label>
            <input type="number" name="recurring_overpayment" value="0"><br><br>

            <button type="submit">Calculate</button>
        </form>
    </div>
    <div class="results-column">
        {% if show_results %}
        <h2>Results</h2>
        <h2>Overpayment Schedule</h2>
        <table>
            <thead>
                <tr>
                    <th>Year</th>
                    <th>Remaining Balance (£)</th>
                    <th>Total Paid (Standard) (£)</th>
                    <th>Total Paid (Overpayment) (£)</th>
                    <th>Overpayment Allowance (£)</th>
                    <th>Monthly Overpayment Available (£)</th>
                    <th>Yearly Overpayment (£)</th>
                    <th>Initial Lump Sum (£)</th>
                </tr>
            </thead>
            <tbody>
                {% for item in overpayment_schedule %}
                <tr>
                    <td>{{ item.year }}</td>
                    <td>{{ item.remaining_balance }}</td>
                    <td>{{ item.total_paid_standard }}</td>
                    <td>{{ item.total_paid_overpayment }}</td>
                    <td>{{ item.overpayment_allowance }}</td>
                    <td>{{ item.monthly_overpayment_available }}</td>
                    <td>{{ item.yearly_overpayment }}</td>
                    <td>{{ item.initial_lump_sum }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

webapp/templates/webapp/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Common Cents{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'webapp/style.css' %}">
</head>
<body>
    <header>
        <h1>{% block heading %}Common Cents{% endblock %}</h1>
    </header>

    <nav>
        <ul class="breadcrumbs">
            <li><a href="/">Home</a></li>
            {% block breadcrumbs %}{% endblock %}
        </ul>
    </nav>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>&copy; 2025 Samuele Mattiuzzo / Common Cents</p>
    </footer>

</body>
</html>

webapp/templates/webapp/index.html
{% extends "webapp/base.html" %}
{% load static %}

{% block title %}Home{% endblock %}
{% block heading %}Common Cents{% endblock %}

{% block content %}
    <div class="grid-container">
        <div class="grid-item">
            <h2>Affordability Calculator</h2>
            <p>Determine how much you can afford to borrow.</p>
            <a href="{% url 'calculators:affordability_calculator' %}"><button>View</button></a>
        </div>
        <div class="grid-item">
            <h2>Overpayment Calculator</h2>
            <p>Calculate your mortgage payments and overpayment schedule.</p>
            <a href="{% url 'calculators:overpayment_calculator' %}"><button>View</button></a>
        </div>
    </div>
{% endblock %}